#!/usr/bin/env python3
"""
Plot CMB power spectrum from CLASS .dat files
This script reads the output files generated by the C executable and plots them.
"""

import numpy as np
import matplotlib.pyplot as plt
import time
import os # For checking if files exist

# Load Planck spectrum data
# Files downloaded from https://cmb.wintherscoming.no/data/
data_folder = './PlanckData_2018/'
planck_files = {
    'TT': data_folder + 'COM_PowerSpect_CMB-TT-full_R3.01.txt',
    'EE': data_folder + 'COM_PowerSpect_CMB-EE-full_R3.01.txt',
    'TE': data_folder + 'COM_PowerSpect_CMB-TE-full_R3.01.txt'
}
planck_lensing_file = data_folder + 'Planck2018_Lensing.dat'


def load_planck_lensing_data():
    """
    Load Planck 2018 lensing power spectrum.

    File columns: l_min  l_center  l_max  power  sigma_power
    where power = 10^7 * [l(l+1)]^2 * C_l^phiphi / (2pi)

    Returns:
        l_center (np.array): bin-centre multipoles
        power    (np.array): lensing power in Planck units
        sigma    (np.array): 1-sigma errors
    """
    empty = np.array([]), np.array([]), np.array([])
    if not os.path.exists(planck_lensing_file):
        print(f"WARNING: Planck lensing file not found: '{planck_lensing_file}'")
        return empty
    try:
        d = np.loadtxt(planck_lensing_file, comments='#', usecols=(1, 3, 4))
        return d[:, 0], d[:, 1], d[:, 2]
    except Exception as e:
        print(f"Error loading Planck lensing data: {e}")
        return empty


def load_planck_data(spec='TT'):
    """
    Load Planck 2018 power spectrum data for TT.

    Returns:
        l      (np.array): multipole values
        Dl     (np.array): D_l [μK²]
        err    (np.array): shape (2, N) — [negative, positive] errors
    """
    filepath = planck_files[spec]
    empty = np.array([]), np.array([]), np.array([np.array([]), np.array([])])

    if not os.path.exists(filepath):
        print(f"WARNING: Planck {spec} file not found: '{filepath}'")
        return empty

    try:
        d = np.loadtxt(filepath, comments='#', usecols=(0, 1, 2, 3))
        return d[:, 0], d[:, 1], np.array([d[:, 2], d[:, 3]])
    except Exception as e:
        print(f"Error loading Planck {spec} data: {e}")
        return empty


def read_class_cl_file(filename):
    """
    Read CLASS Cl output file.
    CLASS columns: 1:l  2:TT  3:EE  4:TE  5:BB  6:phiphi  ...
    All already in l(l+1)/(2pi)*C_l (dimensionless).

    Returns l, cl_tt, cl_ee, cl_te, cl_pp.
    """
    data = np.loadtxt(filename, comments='#')
    l     = data[:, 0].astype(int)
    cl_tt = data[:, 1]
    cl_ee = data[:, 2]
    cl_te = data[:, 3]
    cl_pp = data[:, 5]   # lensing potential: l(l+1)/(2pi) * C_l^phiphi
    return l, cl_tt, cl_ee, cl_te, cl_pp


def plot_class_on_axes(axes, filename, label=None, color=None):
    """
    Plot TT, EE, TE, phiphi theory curves from one CLASS output file onto four Axes.

    Parameters:
    axes    : sequence of four Axes (TT, EE, TE, phiphi)
    filename: path to CLASS _cl_lensed.dat file
    label   : legend label
    color   : line colour
    """
    try:
        l, cl_tt, cl_ee, cl_te, cl_pp = read_class_cl_file(filename)

        T_CMB = 2.7255                 # K
        fac   = (1e6 * T_CMB) ** 2    # dimensionless → μK²

        axes[0].plot(l, cl_tt * fac, label=label, color=color, linewidth=1.5)
        # axes[1].plot(l, cl_ee * fac, label=label, color=color, linewidth=1.5)
        # axes[2].plot(l, cl_te * fac, label=label, color=color, linewidth=1.5)

        # Convert CLASS pp [l(l+1)/(2pi) C_l^phiphi] to Planck lensing units
        # [10^7 * l(l+1)^2 * C_l^phiphi / (2pi)] = 1e7 * l*(l+1) * cl_pp
        if len(axes) > 1:
            cl_pp_planck = 1e7 * l * (l + 1) * cl_pp
            axes[1].plot(l, cl_pp_planck, label=label, color=color, linewidth=1.5)

        print(f"Successfully plotted {filename}")

    except Exception as e:
        print(f"Error reading {filename}: {e}")


# Main plotting
if __name__ == "__main__":

    filename1 = "./class_nu_spacing/output/test_closed_externalPPS00_cl_lensed.dat"
    filename2 = "./class_nu_spacing/output/test_closed_externalPPS01_cl_lensed.dat" 

    # fig, axes = plt.subplots(2, 1, figsize=(9, 9), sharex=True)
    fig, axes = plt.subplots(1, 1, figsize=(9, 6), sharex=True)
    axes = [axes]   # keep axes indexable for the rest of the code

    # --- Planck 2018 data on each panel ---
    planck_labels = {'TT': 'Planck 2018 TT', 'EE': 'Planck 2018 EE', 'TE': 'Planck 2018 TE'}
    # for ax, spec in zip(axes[:3], ['TT', 'EE', 'TE']):
    for ax, spec in zip(axes[:1], ['TT']):
        l_p, Dl_p, err_p = load_planck_data(spec)
        if l_p.size > 0:
            ax.errorbar(l_p, Dl_p, yerr=err_p, fmt='o', color='orange',
                        markersize=3, elinewidth=1, capsize=2, label=planck_labels[spec])

    # # --- Planck 2018 lensing data ---
    # l_lens, power_lens, sigma_lens = load_planck_lensing_data()
    # if l_lens.size > 0:
    #     axes[1].errorbar(l_lens, power_lens, yerr=sigma_lens, fmt='o', color='orange',
    #                      markersize=4, elinewidth=1, capsize=2, label=r'Planck 2018 $C_\ell^{\phi\phi}$')

    # --- CLASS theory curves ---
    plot_class_on_axes(axes, filename1, color='blue', label='conventional CMB spectrum')
    plot_class_on_axes(axes, filename2, color='red',  label='fluctuating PPS (this work)')

    # --- Formatting ---
    ylabels = [
        r'$\mathcal{D}_\ell^{TT}\:[\mu\mathrm{K}^2]$',
        # r'$\mathcal{D}_\ell^{EE}\:[\mu\mathrm{K}^2]$',
        # r'$\mathcal{D}_\ell^{TE}\:[\mu\mathrm{K}^2]$',
        # r'$10^7\,[\ell(\ell+1)]^2\,C_\ell^{\phi\phi}\,/\,(2\pi)$',
    ]
    def autoscale_y(ax, margin=0.05):
        """Rescale y to fit all plotted data within the current x limits."""
        xmin, xmax = ax.get_xlim()
        ymin, ymax = np.inf, -np.inf
        for line in ax.lines:
            x, y = np.asarray(line.get_xdata()), np.asarray(line.get_ydata())
            mask = (x >= xmin) & (x <= xmax)
            if mask.any():
                ymin = min(ymin, np.nanmin(y[mask]))
                ymax = max(ymax, np.nanmax(y[mask]))
        for coll in ax.collections:   # errorbar markers/caps
            offs = coll.get_offsets()
            if len(offs):
                x, y = offs[:, 0], offs[:, 1]
                mask = (x >= xmin) & (x <= xmax)
                if mask.any():
                    ymin = min(ymin, np.nanmin(y[mask]))
                    ymax = max(ymax, np.nanmax(y[mask]))
        if np.isfinite(ymin) and np.isfinite(ymax):
            span = ymax - ymin
            ax.set_ylim(ymin - margin * span, ymax + margin * span)

    for ax, ylabel in zip(axes, ylabels):
        ax.set_xscale('log')
        ax.grid(True, alpha=0.3)
        ax.set_ylabel(ylabel, fontsize=13)
        ax.tick_params(axis='both', which='major', labelsize=13)
        ax.legend(fontsize=11)
        autoscale_y(ax)

    axes[-1].set_xlabel(r'$\ell$', fontsize=13)
    fig.suptitle("CMB Power Spectra — external PPS", fontsize=14)
    fig.tight_layout()
    fig.savefig('./figures/CMB_TT_externalPPS.pdf')
    print("Saved ./figures/CMB_TT_externalPPS.pdf")
